[tool.black]
line-length = 79
skip-string-normalization = 1
target-version = ['py39']

[tool.isort]
py_version = 39
src_paths = ['api', 'weather', 'weather_api']
profile = 'black'
skip = ['migrations', 'venv',]
line_length=79