# Generated by Django 4.2 on 2025-06-08 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=150, verbose_name='название'),
                ),
                ('date', models.DateField(verbose_name='дата прогноза')),
                (
                    'min_temperature',
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-100),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name='минимальная температура',
                    ),
                ),
                (
                    'max_temperature',
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-100),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name='максимальная температура',
                    ),
                ),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AddConstraint(
            model_name='forecast',
            constraint=models.UniqueConstraint(
                fields=('name', 'date'), name='unique_weather_forecast'
            ),
        ),
    ]
