# Generated by Django 4.2 on 2025-06-08 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_remove_forecast_unique_weather_forecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='city',
            field=models.CharField(
                max_length=150, verbose_name='name of location'
            ),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='max_temperature',
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-100),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name='maximum temperature',
            ),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='min_temperature',
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-100),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name='minimal temperature',
            ),
        ),
    ]
