# Generated by Django 4.2 on 2025-06-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_forecast_city_alter_forecast_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecast',
            options={
                'ordering': ('-date',),
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
    ]
